version: '3'

services:
  db:
    image: mysql:8.0
    volumes:
      - todo-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-password
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

volumes:
  todo-data:
    driver: local
